#!/usr/bin/env bash
# Adopt an existing ceph-csi RBD volume under Bard CSI -- IN PLACE, no data copy.
#
# WHY: a ceph-csi RBD volume is just an rbd image in a pool. Bard's node plane
# maps `<pool>/<image>` straight out of the volume handle (see the static-volume
# support, deploy/examples/static/), so the SAME image can be re-wrapped under a
# Bard PersistentVolume with zero bytes moved. This is the migration path for
# adopters coming off ceph-csi: the image stays where it is; only the PV/PVC
# objects (and the driver that owns them) change.
#
# This script does NOT mutate anything. It reads a bound ceph-csi PVC, derives
# (instance, pool, image), and PRINTS:
#   - stdout: the Bard static PV + PVC manifest (apply it during cutover)
#   - stderr: the exact, ordered cutover runbook (reclaim dance + image-meta)
# Run the printed steps yourself, with the workload scaled down. See
# deploy/examples/migrate-ceph-csi/README.md for the full procedure + caveats.
#
#   hack/adopt-ceph-csi-rbd.sh -n <ns> -c <pvc> -i <bard-instance> [-o out.yaml]
#
# <bard-instance> is the instance/zone id from your bard-ceph-config that points
# at the SAME Ceph cluster + pool the ceph-csi volume lives in (it selects the
# cephx key). The script cannot infer it from the ceph-csi clusterID, so you
# supply it.
set -euo pipefail

export PATH="$HOME/.local/bin:$HOME/sdk/go/bin:$PATH"

NS="" PVC="" INSTANCE="" OUT="" ALLOW_ENC=0
die() { echo "error: $*" >&2; exit 1; }
usage() { sed -n '2,28p' "$0" >&2; exit 2; }

while [ $# -gt 0 ]; do
  case "$1" in
    -n) NS="$2"; shift 2;;
    -c) PVC="$2"; shift 2;;
    -i) INSTANCE="$2"; shift 2;;
    -o) OUT="$2"; shift 2;;
    --allow-encrypted) ALLOW_ENC=1; shift;;
    -h|--help) usage;;
    *) die "unknown argument: $1";;
  esac
done
[ -n "$NS" ] && [ -n "$PVC" ] && [ -n "$INSTANCE" ] || usage

kget() { kubectl get "$@"; }

# 1. Resolve the bound PV behind the source PVC.
PV="$(kget pvc -n "$NS" "$PVC" -o jsonpath='{.spec.volumeName}')"
[ -n "$PV" ] || die "PVC $NS/$PVC is not bound to a PV (status $(kget pvc -n "$NS" "$PVC" -o jsonpath='{.status.phase}'))"

PVJSON="$(kget pv "$PV" -o json)"
field() { jq -r "$1 // empty" <<<"$PVJSON"; }

DRIVER="$(field '.spec.csi.driver')"
[ -n "$DRIVER" ] || die "PV $PV has no .spec.csi (not a CSI volume?)"
case "$DRIVER" in
  *rbd.csi.ceph.com*) : ;;
  *) echo "warning: PV driver is '$DRIVER', not 'rbd.csi.ceph.com' -- proceeding, but verify this is a ceph-csi RBD volume." >&2;;
esac

HANDLE="$(field '.spec.csi.volumeHandle')"
POOL="$(field '.spec.csi.volumeAttributes.pool')"
IMAGE="$(field '.spec.csi.volumeAttributes.imageName')"
# Fallback: ceph-csi names the image csi-vol-<uuid>, and the uuid is the trailing
# 36 chars of the handle (0001-<clusterIDlen>-<clusterID>-<poolID>-<uuid>).
if [ -z "$IMAGE" ] && [ -n "$HANDLE" ]; then
  UUID="${HANDLE: -36}"
  IMAGE="csi-vol-${UUID}"
  echo "note: imageName not in volumeAttributes; derived '$IMAGE' from the handle uuid." >&2
fi
[ -n "$POOL" ]  || die "could not determine the rbd pool from PV $PV (.spec.csi.volumeAttributes.pool empty) -- pass it in manually by editing the output."
[ -n "$IMAGE" ] || die "could not determine the rbd image name from PV $PV."

ENC="$(field '.spec.csi.volumeAttributes.encrypted')"
ENC_KMS="$(field '.spec.csi.volumeAttributes.encryptionKMSID')"
if [ "$ENC" = "true" ] && [ "$ALLOW_ENC" -eq 0 ]; then
  die "PV $PV is ceph-csi-ENCRYPTED (encrypted=true). Bard cannot decrypt a ceph-csi LUKS image without bridging its KMS/passphrase, so in-place adoption is unsafe by default. See the README 'Encrypted volumes' section; re-run with --allow-encrypted only if you have arranged a matching passphrase."
fi

CAP="$(field '.spec.capacity.storage')"
VOLMODE="$(field '.spec.volumeMode')"; [ -n "$VOLMODE" ] || VOLMODE="Filesystem"
FSTYPE="$(field '.spec.csi.fsType')"; [ -n "$FSTYPE" ] || FSTYPE="ext4"
RECLAIM="$(field '.spec.persistentVolumeReclaimPolicy')"
mapfile -t MODES < <(jq -r '.spec.accessModes[]?' <<<"$PVJSON")
[ "${#MODES[@]}" -gt 0 ] || MODES=("ReadWriteOnce")

BARD_HANDLE="swsk|1|ceph-rbd|${INSTANCE}|${POOL}|${IMAGE}"
NEWPV="bard-${PVC}"

emit_modes() { for m in "${MODES[@]}"; do echo "    - ${m}"; done; }

gen() {
cat <<YAML
# Generated by hack/adopt-ceph-csi-rbd.sh -- in-place adoption of a ceph-csi RBD
# volume under Bard CSI. Source: PVC ${NS}/${PVC} -> PV ${PV} (driver ${DRIVER}).
# The rbd image ${POOL}/${IMAGE} is reused as-is; no data is copied.
# Apply this ONLY as part of the cutover runbook (workload scaled down, source
# PV set to Retain, source PVC/PV deleted). See README.md.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${NEWPV}
spec:
  capacity:
    storage: ${CAP}
  accessModes:
$(emit_modes)
  volumeMode: ${VOLMODE}
  # Retain: the adopted image is pre-existing; Kubernetes must never reap it.
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: csi.bard.io
    # swsk|1|ceph-rbd|<instance>|<pool>|<image> -- instance selects the cluster +
    # cephx key from bard-ceph-config; pool/image name the existing rbd image.
    volumeHandle: "${BARD_HANDLE}"
$( [ "$VOLMODE" = "Filesystem" ] && echo "    fsType: ${FSTYPE}" )
    volumeAttributes:
      pool: ${POOL}
      imageName: ${IMAGE}
$( [ "$ENC" = "true" ] && echo "      # ceph-csi-encrypted image: the node plane will attempt LUKS open. You MUST" )
$( [ "$ENC" = "true" ] && echo "      # supply the SAME passphrase ceph-csi used (e.g. an encryptionPassphrase CSI" )
$( [ "$ENC" = "true" ] && echo "      # secret), or arrange a matching Bard KMS. See README 'Encrypted volumes'." )
$( [ "$ENC" = "true" ] && echo "      encrypted: \"true\"" )
$( [ "$ENC" = "true" ] && [ -n "$ENC_KMS" ] && echo "      encryptionKMSID: \"${ENC_KMS}\"" )
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${PVC}
  namespace: ${NS}
spec:
  accessModes:
$(emit_modes)
  volumeMode: ${VOLMODE}
  storageClassName: ""
  resources:
    requests:
      storage: ${CAP}
  volumeName: ${NEWPV}
YAML
}

# Conditional $(...) lines that expand to nothing still leave a blank line; this
# YAML has no intentional blank lines, so drop whitespace-only lines for clean output.
strip_blank() { grep -v '^[[:space:]]*$'; }
if [ -n "$OUT" ]; then gen | strip_blank >"$OUT"; echo "wrote manifest -> $OUT" >&2; else gen | strip_blank; fi

# Cutover runbook on stderr so it never pollutes the manifest on stdout.
RBD="rbd -p ${POOL}"
cat >&2 <<RUNBOOK

================  CUTOVER RUNBOOK (run these yourself, in order)  ================
Source : PVC ${NS}/${PVC}  ->  PV ${PV}  (ceph-csi)
Target : reuse rbd image ${POOL}/${IMAGE} under Bard instance '${INSTANCE}'
         (no data copied; image stays in place)

PRECHECK
  - The workload using ${NS}/${PVC} MUST be scaled to 0 for the cutover (one
    image, one writer). This is a brief restart, NOT a data copy.
  - The Bard instance '${INSTANCE}' in bard-ceph-config must reach pool '${POOL}'
    on the same Ceph cluster, with a cephx user that can map the image.

1) Scale the workload down (release the mount):
     kubectl -n ${NS} scale <deploy/sts> --replicas=0   # your workload

2) Keep the image when the ceph-csi PVC is deleted (Retain so DeleteVolume is
   never called):
     kubectl patch pv ${PV} -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}'

3) Defence in depth -- mark the image static so even a stray Bard DeleteVolume
   is a no-op:
     ${RBD} image-meta set ${IMAGE} bard.static true

4) Delete the ceph-csi PVC, then its now-Released PV (image is untouched):
     kubectl -n ${NS} delete pvc ${PVC}
     kubectl delete pv ${PV}

5) Bind the image to Bard (apply the generated manifest):
     kubectl apply -f ${OUT:-the-manifest-above.yaml}

6) Scale the workload back up -- kubelet NodeStage maps the SAME image via Bard:
     kubectl -n ${NS} scale <deploy/sts> --replicas=1

ROLLBACK: nothing destructive happened to the image. To revert, delete the Bard
PVC/PV and re-create the original ceph-csi PV/PVC (or restore from your backup of
the ceph-csi PV object). Capacity on the Bard PV is copied from the source
(${CAP}); it must match the real image size.
=================================================================================
RUNBOOK
