#!/usr/bin/env bash
# Copy-migrate a PVC from ANY CSI / provisioner into a Bard CSI PVC.
#
# WHY: in-place adoption (hack/adopt-ceph-csi-rbd.sh) only works when the source
# is already an rbd image Bard can re-wrap. To migrate from a *different* backend
# -- AWS EBS, GCE-PD, NFS, hostPath/local-path, anything that presents a PVC --
# the bytes have to move. This is backend-agnostic: a Job mounts the source PVC
# read-only and a freshly-provisioned Bard PVC, and copies (rsync for a
# filesystem volume, dd for a raw block volume), then verifies by checksum.
#
# The source MUST be quiesced during the copy or the result is inconsistent. For
# an RWO source that is automatic: the source's workload pod holds the single
# attach, so the copy Job stays Pending until you scale the workload to 0. The
# script refuses --run while the source PVC is mounted.
#
#   hack/migrate-copy.sh -n <ns> -c <source-pvc> -s <bard-storageclass> \
#       [-t <target-pvc>] [-m fs|block] [--run] [-o out.yaml]
#
# Default is generate-only: prints the target Bard PVC + copy Job on stdout and
# the cutover runbook on stderr. --run applies them and waits for the copy to
# verify. -t defaults to "<source-pvc>-bard"; -m auto-detects from the source
# volumeMode. See deploy/examples/migrate-copy/README.md.
set -euo pipefail

export PATH="$HOME/.local/bin:$HOME/sdk/go/bin:$PATH"

NS="" SRC="" SC="" TGT="" MODE="" OUT="" RUN=0
die() { echo "error: $*" >&2; exit 1; }
usage() { sed -n '2,26p' "$0" >&2; exit 2; }

while [ $# -gt 0 ]; do
  case "$1" in
    -n) NS="$2"; shift 2;;
    -c) SRC="$2"; shift 2;;
    -s) SC="$2"; shift 2;;
    -t) TGT="$2"; shift 2;;
    -m) MODE="$2"; shift 2;;
    -o) OUT="$2"; shift 2;;
    --run) RUN=1; shift;;
    -h|--help) usage;;
    *) die "unknown argument: $1";;
  esac
done
[ -n "$NS" ] && [ -n "$SRC" ] && [ -n "$SC" ] || usage
[ -n "$TGT" ] || TGT="${SRC}-bard"

SRCJSON="$(kubectl get pvc -n "$NS" "$SRC" -o json)"
sf() { jq -r "$1 // empty" <<<"$SRCJSON"; }
[ "$(sf '.status.phase')" = "Bound" ] || die "source PVC $NS/$SRC is not Bound"

# Capacity from the bound PV's actual capacity (status), falling back to request.
CAP="$(sf '.status.capacity.storage')"; [ -n "$CAP" ] || CAP="$(sf '.spec.resources.requests.storage')"
[ -n "$CAP" ] || die "could not determine source PVC capacity"
VOLMODE="$(sf '.spec.volumeMode')"; [ -n "$VOLMODE" ] || VOLMODE="Filesystem"
mapfile -t MODES < <(jq -r '.spec.accessModes[]?' <<<"$SRCJSON")
[ "${#MODES[@]}" -gt 0 ] || MODES=("ReadWriteOnce")

# Mode: explicit -m wins, else derive from volumeMode.
if [ -z "$MODE" ]; then [ "$VOLMODE" = "Block" ] && MODE="block" || MODE="fs"; fi
case "$MODE" in fs) VOLMODE="Filesystem";; block) VOLMODE="Block";; *) die "-m must be fs or block";; esac

emit_modes() { for m in "${MODES[@]}"; do echo "    - ${m}"; done; }

# The copy+verify program the Job runs (rsync for fs, dd for block), self-checking.
if [ "$MODE" = "fs" ]; then
  COPY_PROG='set -e
apk add --no-cache rsync >/dev/null 2>&1 || { echo "apk add rsync failed (need egress)"; exit 1; }
echo "[copy] rsync /src -> /dst"
rsync -aHAXS --numeric-ids --delete --exclude=/lost+found --info=stats2 /src/ /dst/
sync
echo "[verify] checksum manifest /src vs /dst"
a=$(cd /src && find . -type f ! -path "./lost+found/*" -print0 | sort -z | xargs -0 md5sum 2>/dev/null | md5sum)
b=$(cd /dst && find . -type f ! -path "./lost+found/*" -print0 | sort -z | xargs -0 md5sum 2>/dev/null | md5sum)
echo "src=$a"; echo "dst=$b"
[ "$a" = "$b" ] && echo "MIGRATE_COPY_OK" || { echo "MIGRATE_COPY_VERIFY_FAILED"; exit 1; }'
else
  COPY_PROG='set -e
sz=$(blockdev --getsize64 /dev/src)
echo "[copy] dd /dev/src ($sz bytes) -> /dev/dst"
dd if=/dev/src of=/dev/dst bs=4M conv=fsync
echo "[verify] cmp over source length"
cmp -n "$sz" /dev/src /dev/dst && echo "MIGRATE_COPY_OK" || { echo "MIGRATE_COPY_VERIFY_FAILED"; exit 1; }'
fi

JOB="bard-migrate-${SRC}"

gen() {
cat <<YAML
# Generated by hack/migrate-copy.sh -- copy-migrate ${NS}/${SRC} (${MODE}) into a
# Bard CSI PVC on StorageClass '${SC}'. The source bytes are copied, not re-wrapped;
# use this for non-RBD sources (in-place adoption is better when it applies).
# Apply ONLY with the source workload scaled to 0 (consistency). See README.md.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${TGT}
  namespace: ${NS}
spec:
  accessModes:
$(emit_modes)
  volumeMode: ${VOLMODE}
  storageClassName: ${SC}
  resources:
    requests:
      storage: ${CAP}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB}
  namespace: ${NS}
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: copy
          image: alpine:3.20
          command: ["/bin/sh","-c"]
          args:
            - |
$(printf '%s\n' "$COPY_PROG" | sed 's/^/              /')
YAML
if [ "$MODE" = "fs" ]; then
cat <<YAML
          volumeMounts:
            - { name: src, mountPath: /src, readOnly: true }
            - { name: dst, mountPath: /dst }
YAML
else
cat <<YAML
          volumeDevices:
            - { name: src, devicePath: /dev/src }
            - { name: dst, devicePath: /dev/dst }
YAML
fi
cat <<YAML
      volumes:
        - name: src
          persistentVolumeClaim: { claimName: ${SRC}, readOnly: true }
        - name: dst
          persistentVolumeClaim: { claimName: ${TGT} }
YAML
}

if [ -n "$OUT" ]; then gen >"$OUT"; echo "wrote manifest -> $OUT" >&2; elif [ "$RUN" -eq 0 ]; then gen; fi

# Runbook (stderr -- never pollutes the manifest on stdout).
cat >&2 <<RUNBOOK

================  COPY-MIGRATE RUNBOOK (${NS}/${SRC} -> ${TGT}, ${MODE})  ========
Source : PVC ${NS}/${SRC}  (${CAP}, ${MODES[*]})
Target : new Bard PVC ${NS}/${TGT} on StorageClass '${SC}' -- bytes COPIED

1) Quiesce the source -- scale its workload to 0 (REQUIRED for a consistent copy):
     kubectl -n ${NS} scale <deploy|statefulset>/<name> --replicas=0

2) Run the copy Job (this script with --run, or apply the manifest):
     hack/migrate-copy.sh -n ${NS} -c ${SRC} -s ${SC} -t ${TGT} -m ${MODE} --run
   Wait for the pod log to print MIGRATE_COPY_OK (rsync/dd + checksum verify).

3) Repoint your workload to ${TGT}. Either:
   (a) edit the workload's claimName: ${SRC} -> ${TGT}, or
   (b) keep the original name -- Retain ${TGT}'s PV, delete BOTH PVCs, then
       recreate a PVC named ${SRC} bound to the populated Bard PV (volumeName).

4) Scale the workload back up; verify your app, THEN delete the old source PVC
   (and its backend volume) once you are satisfied.

ROLLBACK before step 4: the source is untouched (mounted read-only); just delete
${TGT} and the Job and scale the original workload back up.
=================================================================================
RUNBOOK

[ "$RUN" -eq 1 ] || exit 0

# --run: refuse if the source is still mounted (inconsistent copy), then apply+wait.
INUSE="$(kubectl get pods -n "$NS" -o json | jq -r --arg c "$SRC" \
  '.items[] | select(.spec.volumes[]?.persistentVolumeClaim.claimName==$c) | .metadata.name')"
[ -z "$INUSE" ] || die "source PVC $SRC is still mounted by pod(s): $INUSE -- scale the workload to 0 first (step 1)"

echo "==> applying target PVC + copy Job" >&2
gen | kubectl apply -f - >&2
echo "==> waiting for copy Job to complete (this moves data; large volumes take a while)" >&2
if kubectl -n "$NS" wait --for=condition=complete "job/${JOB}" --timeout=1800s >&2 2>&1; then
  kubectl -n "$NS" logs "job/${JOB}" 2>/dev/null | tail -6 >&2
  echo "==> COPY COMPLETE + VERIFIED. Now do runbook step 3 (repoint) + step 4." >&2
else
  echo "==> copy Job did NOT complete; logs:" >&2
  kubectl -n "$NS" logs "job/${JOB}" 2>/dev/null | tail -20 >&2
  die "copy failed -- source untouched; inspect job/${JOB} in ns ${NS}"
fi
